### ISSUE TITLE
Should/must/may

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/guide#1]
Noticed a lot of "shoulds" in the guide. Is this intentional or accidental? In the spirit of conventional defaults over customization, why not use more binding language ("will", "must")?

Also, we could explicitly invoke and follow RFC 2119 https://www.ietf.org/rfc/rfc2119.txt.

**Comment by shereefb** [comment]
I don't like shoulds. I much prefer declarative, and if we have to prescriptive.
