### ISSUE TITLE
Privacy with guild therapist

### ISSUE THREAD

**Issue by lumodon** [LearnersGuild/guide#122]
There's a section under Game Manual -> Boundries -> "What will NOT be used to kick off an Investment Re-Evaluation"

It claims that "Any information/data from the therapist" will "NOT be used to kick off an Investment Re-Evaluation"

This implies that the therapist shares information and data with facilitators, which implies that our conversations with the therapist are not confidential. 

This needs a re-wording to show that the therapist DOESN'T share confidential information, AND thereby, that information which wasn't shared WON'T be used to kick off an Investment Re-Evaluation. 

I don't have a recommendation on how to re-word it to clarify. Anybody have an idea how to word this more clearly?

**Comment by Josh5231** [comment]
This issue should be closed. New line reads:
Any information/data from the therapist (staff never talks to the therapists about specific learners)

**Comment by lumodon** [comment]
Resolved as noted https://github.com/LearnersGuild/guide/issues/122#issuecomment-300276975
