### ISSUE TITLE
Contribution Guideline has broken links

### ISSUE THREAD

**Issue by lumodon** [LearnersGuild/guide#123]
The [Contribution Guideline](https://github.com/LearnersGuild/playbook/blob/master/CONTRIBUTING.md) has a broken link under the "To learn about GitBook, start by reading the following documentation:" unordered list.

**Chapters and Subchapters** points to http://help.gitbook.com/format/chapters.html
that link is broken, including the `/format/` link, and finally using only the domain: `help.gitbook.com` and searching for "chapters" doesn't yield any results. Where was this supposed to point to?

Possible that other links could be broken too. (Will test later and update this issue as I get time.)

**Comment by Josh5231** [comment]
I went back through the history of this file and it seems that there never was a format folder. I'm guessing that this was on someone's todo list and just never got done or got missed on the initial push.  All the links for files in format and editor folder are broken.
http://help.gitbook.com/format/chapters.html
http://help.gitbook.com/format/index.html
http://help.gitbook.com/format/output.html
http://help.gitbook.com/format/introduction.html
http://help.gitbook.com/format/markdown.html
http://help.gitbook.com/editor/index.html
