### ISSUE TITLE
Add pairing practice for runway

### ISSUE THREAD

**Issue by shereefb** [LearnersGuild/guide#20]
Guidance to meet other learners on echo, setup a pairing environment with them (or meet in person) and work on some challenges together.

**Comment by tannerwelsh** [comment]
I'm gonna punt on this for now. Learning to pair remotely is a significant lift, and I don't know if we should set an expectation that learners should be pairing before their start date.

Not to say that learners can't decide to screenshare while conversing in Echo, or that they can't work on challenges together from Echo. I just think that asking learners to pair this early is a less efficient/effective use of their time. Lots of other skills are better learned on ones own.

(Also the runway is getting pretty bloated - there's a ton of stuff in there already)
