### ISSUE TITLE
Tense and voice

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/guide#3]
Should language be in present or future tense?

"Partners operate under the assumption that..." vs. "Partners will operate under the assumption that..."

Should the tone be directive, prescriptive, or declarative?

Directive: "Partners will touch their noses upon meeting each other"
Prescriptive: "Partners should touch their noses upon meeting each other"
Declarative: "Partners touch their noses upon meeting each other"

**Comment by shereefb** [comment]
Prescriptive lends itself too much to be a super ego. Imposed from the outside. Like a command or an order. Doesn't inspire me. Reads like a rule book.

Directive can sound like it lacks humility, and is describing the future. Something that isn't happening yet, and hasn't happened yet. 

My favorite is declarative. It's audacious, and can seem grandiose, but it speaks as though things already are. Let's use that.
