### ISSUE TITLE
Outline Player Statistics

### ISSUE THREAD

**Issue by jrobcodes** [LearnersGuild/guide#31]
## Strategic Goals this issues impacts
- !Learner stats match our subjective reality, elicit honest feedback, and promote self-directed, collaborative growth
- !Players know how to increase low stats

It would be helpful and informative to have the player statistics and metrics enumerated and defined in the playbook.  Could also be useful to have some information about how to optimize these stats while playing, or information about tensions between statistics (i.e. if I optimize for contribution, am I losing out on other metrics).

@tannerwelsh provided me links that begin to define these: 
- https://github.com/LearnersGuild/game/issues/111
- https://github.com/LearnersGuild/learning-os

**Comment by shereefb** [comment]
## Strategic Goals this issues impacts
- !Learner stats match our subjective reality, elicit honest feedback, and promote self-directed, collaborative growth
- !Game is balanced
- !Players know how to increase low stats
- Game feedback loops are all closed
- Goal library is more useful

**Comment by tannerwelsh** [comment]
Closing this since we have a pretty good outline of stats now. If the content of https://playbook.learnersguild.org/Game_Manual/Stats.html doesn't meet what you had in mind for this issue @jrob8577, please re-open.
