### ISSUE TITLE
Define background reading for onboarding

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/guide#4]
What articles/books should new partners be given?

**Comment by shereefb** [comment]
**Must Read:**
Holacracy
Getting Things Done

**Good to Read:**
Deschooling Society
http://www.amazon.com/Deschooling-Society-Open-Forum-S/dp/0714508799
http://learning.media.mit.edu/courses/mas713/readings/DESCHOOLING.pdf
Soul without Shame
