### ISSUE TITLE
Update pod start dates (include locations and no. of pods)

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/guide#41]
The pod start dates in the calendar are not accurate.

Update calendar w/ new dates, locations, and no. of pods per date.

**Comment by tannerwelsh** [comment]
Waiting on start date decision finalized: https://app.asana.com/0/83826882527151/91701518302982

**Comment by shereefb** [comment]
Tentatively here's the latest thought right now:

11-Jul	Oakland
15-Aug	NY
19-Sep	Oakland
24-Oct	NY
28-Nov	Oakland
9-Jan	NY
13-Feb	Oakland
20-Mar	NY
24-Apr	Oakland
29-May	NY

**Comment by shereefb** [comment]
One thing I've been thinking is that we should skip 15-Aug NY. Do Oakland, 10 weeks later another Oakland, 5 weeks later NY.

**Comment by tannerwelsh** [comment]
So Oak would be 7/11, 9/19, and then NY starts 10/24, and each location goes in 10-week intervals from there on out?

That would work better for me, given how much focus LOS is needing.

**Comment by shereefb** [comment]
Decision done.

We are staggering. 5 weeks apart across locations. 10 weeks apart start dates for same location.

Oakland: July 11th  1 POD
Oakland: September 19th 2 PODS
NYC: October 24th 1 POD

More details here: 

https://docs.google.com/a/learnersguild.org/spreadsheets/d/1TsTIcD48K6tZQhMZjhBIZEXO9cTS7abCAMwNTP50wfg/edit?usp=sharing
