### ISSUE TITLE
Fix broken Wistia embed, link to video instead

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/guide#46]
This change doesn't play nice with GitBook: https://github.com/LearnersGuild/playbook/pull/45/commits/54e6893a23e31a5bb0315be5b4ce3b25c5b4d673

See the live version: http://playbook.learnersguild.org/General/Guidelines.html

Please replace with a link to the video, instead of embedding it. Wasn't clear to me from the code where the original video was.

**Comment by tannerwelsh** [comment]
\cc @shereefb

**Comment by shereefb** [comment]
fixed
