### ISSUE TITLE
Address question: "am I on track?"

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/guide#70]
## Critical Strategic Goals
- !Players know how to increase low stats
- !Learners quickly understand how to play the game
- !Learners spending the majority of their time working on relevant strechy goals
### Draft

Am I on track?
- Validate this is a great question to ask. Define two different meanings of on track:
1. I'm gong to be a web developer eventually
2. I'm going to be a web developer in 10 months

Answer to 1: Yes if your numbers are going up week over week
Answer to 2: Yes if your numbers are going up week over week AND at a good rate.

What good rate is, is hard to define right now. We'll have more data once pods 1,2,3 get job offers. And we'll invite outside people to come build software with us so we can compare our skills with theirs, and we'll do mock interviews.

What should I work on next?
- Get guidance from pro players, and people who have been ahead of you. Constantly ask yourself this question. Find a good map of competencies and make sure you're covering them. Share the map with other players

(from @shereefb's [task request](https://app.asana.com/0/62830781673321/187929976138907))

**Comment by shereefb** [comment]
Issue moved to [LearnersGuild/game-prototype #158](https://github.com/LearnersGuild/game-prototype/issues/158) via [**ZenHub**](https://www.zenhub.com/)
