### ISSUE TITLE
Inline comment bug

### ISSUE THREAD

**Issue by jason00111** [LearnersGuild/guide#79]
When I tried to comment on the playbook by clicking the plus button and adding a comment I got the following error:
> Error with inline comments: Missing required parameter "title"

**Comment by heyheyjp** [comment]
![screen shot 2016-11-16 at 8 07 05 pm](https://cloud.githubusercontent.com/assets/1890882/20376085/8790ca28-ac38-11e6-9187-998ddf1c1a3d.png)

**Comment by tannerwelsh** [comment]
I wasn't able to replicate the bug. Also, afraid this site is hosted by GitBook, not us. So there wouldn't be much we could do to fix it anyway.

@jason00111 if you want to post a bug report to Gitbook, I'd suggest sharing at least:

- Which browser you were on
- Whether you were logged in to Gitbook (via GitHub)
- Which page you tried to comment on
- What text you added to the field

**Comment by jason00111** [comment]
I just tried to comment again and it worked.

Either GitBook fixed the bug or there is something else going on that I'm not aware of. Either way, it looks like the issue is resolved.
