### ISSUE TITLE
Decouple communication points from individuals

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/guide#8]
The guide should not direct users to contact specific people (e.g. "email bonnie@learnersguild.org for IT questions").

If we're going Holacracy, we should be directing all needs/tensions to **roles**.

Could this be built into email structure for key roles? E.g. "contact it@learnersguild.org for IT questions"

**Comment by shereefb** [comment]
Agreed.

The only exception is the board@lg  email used for reporting me!
