### ISSUE TITLE
ELO formula

### ISSUE THREAD

**Issue by jason00111** [LearnersGuild/guide#80]
I wish I could see the formula for ELO.

My guess is something like

`lastWeeksElo + yourContributionPercentage - ( lastWeeksElo / sum(teamMembersElo) )`

but I've also heard that our ELO is not 'zero-sum' (one person's gain is another's expense).

**Comment by jeffreywescott** [comment]
See also [this related Asana task](https://app.asana.com/0/56975740003731/234601971873412) and let me know if / how I can help.

**Comment by tannerwelsh** [comment]
Took a stab at it w/ #90, although granted that since we use an external library you'll still have to look up the math in the library.

@jason00111 does #90 satisfy this issue?

**Comment by jason00111** [comment]
@tannerwelsh Thanks!  It does.

**Comment by tannerwelsh** [comment]
Great! Glad to hear
