### ISSUE TITLE
ESI vs EE

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/guide#9]
Is there any reason to use Engineering Empathy over the (increasingly commonly used) Emotional and Social Intelligence?

My thoughts:

- EE has the word engineering in it. We aren't about engineering, we're about learning.
- EE is a misnomer, since it covers more than empathy. It also covers self-empathy (which is kindof a silly term in itself).

**Comment by shereefb** [comment]
+1. Let's shift to ESI.
